name: CD

on:
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Code Checkout
        uses: actions/checkout@v7

      - name: Copy Example Env to main env
        run: cp .env.example .env

      - name: Install Docker (if not installed)
        run: |
          if ! command -v docker >/dev/null 2>&1; then
            curl -fsSL https://get.docker.com | sh
          fi

          sudo systemctl enable docker
          sudo systemctl start docker

      - name: Install Docker Compose Plugin (if not installed)
        run: |
          if ! sudo docker compose version >/dev/null 2>&1; then
            sudo mkdir -p /usr/local/lib/docker/cli-plugins

            sudo curl -SL \
              https://github.com/docker/compose/releases/latest/download/docker-compose-linux-$(uname -m) \
              -o /usr/local/lib/docker/cli-plugins/docker-compose

            sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          fi

          sudo docker compose version

      - name: Docker Setup [Login]
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy the containers with Docker Compose
        run: sudo docker compose up -d