server {
    # Non-root users cannot bind to privileged ports (< 1024), so we use port 8080
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
