name: devboard-prod

services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-devboard}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devboardpassword}
      POSTGRES_DB: ${POSTGRES_DB:-devboard}
    volumes:
      - prod_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devboard -d devboard"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: rayyan12311/devboard-backend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      POSTGRES_URL: "postgres://devboard:devboardpassword@postgres:5432/devboard?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: rayyan12311/devboard-frontend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "80:8080"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  prod_pgdata:
